github: [Okami, OkamiMks]
patreon: "https://www.patreon.com/OkamiMks"
ko_fi: "https://ko-fi.com/okamimks"
liberapay: "https://liberapay.com/Okami/"
custom: "https://www.paypal.com/donate?hosted_button_id=NKQEXWK3RQDPQ&source=url"
